# Generated by Django 4.2 on 2024-09-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='can_delete',
        ),
    ]
